
service: alerts-for-new-resources

frameworkVersion: '3'

provider:
  name: aws

resources:
   Resources:
     snsTopic: 
       Type: AWS::SNS::Topic
       Properties:
         TopicName: new-alerts-creation-alert
     MySnsSubscription:
       Type: AWS::SNS::Subscription
       Properties:
         Endpoint: support@bizcloudexperts.com
         Protocol: email
         TopicArn: !Ref snsTopic
    
     snspolicy:
       Type: AWS::SNS::TopicPolicy
       Properties:
         PolicyDocument:
           Version: '2008-10-17'
           Id: '__default_policy_ID'
           Statement:
            - Sid: '__default_statement_ID'
              Effect: Allow
              Principal:
                AWS: "*"
              Action:
                - 'SNS:GetTopicAttributes'
                - 'SNS:SetTopicAttributes'
                - 'SNS:AddPermission'
                - 'SNS:RemovePermission'
                - 'SNS:DeleteTopic'
                - 'SNS:Subscribe'
                - 'SNS:ListSubscriptionsByTopic'
                - 'SNS:Publish'
              Resource: !Ref snsTopic
              Condition:
               StringEquals:
                 AWS:SourceOwner: !Ref AWS::AccountId
            - Sid: '1-new-recources-creation-alert-123'
              Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: 'sns:Publish'
              Resource: !Ref snsTopic
         Topics: 
          - !Ref snsTopic

     eventbridgeone:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: default
        EventPattern: 
          !Sub |
            {
              "source": ["aws.config"],
              "detail-type": ["Config Configuration Item Change"],
              "detail": {
                "messageType": ["ConfigurationItemChangeNotification"],
                "configurationItem": {
                  "resourceType": ["AWS::EC2::Instance", "AWS::EC2::Volume", "AWS::EC2::RegisteredHAInstance", "AWS::ElasticLoadBalancingV2::LoadBalancer", "AWS::RDS::DBInstance", "AWS::RDS::DBCluster", "AWS::S3::Bucket", "AWS::Redshift::Cluster", "AWS::ElasticLoadBalancing::LoadBalancer", "AWS::DynamoDB::Table", "AWS::CodeBuild::Project", "AWS::CloudFront::Distribution", "AWS::Lambda::Function", "AWS::KMS::Key", "AWS::Pinpoint::Campaign", "AWS::Backup::BackupPlan", "AWS::ECR::Repository", "AWS::ECS::Cluster", "AWS::ECS::Service", "AWS::EFS::FileSystem", "AWS::EKS::Cluster", "AWS::Kinesis::Stream", "AWS::ECR::PublicRepository", "AWS::DMS::ReplicationInstance", "AWS::MSK::Cluster", "AWS::StepFunctions::Activity", "AWS::SageMaker::Model", "AWS::Glue::Job"],
                  "configurationItemStatus": ["ResourceDiscovered"]
                }
              }
            }

        Name: new-recources-creation-alert-1
        Targets: 
          - Arn: !Ref snsTopic
            Id: new-recources-creation-alert-1
            InputTransformer:
              InputPathsMap:
                "awsAccountId" : "$.detail.configurationItem.awsAccountId"
                "awsRegion" : "$.detail.configurationItem.awsRegion"
                "configurationItemCaptureTime": "$.detail.configurationItem.configurationItemCaptureTime"
                "resource_ID" : "$.detail.configurationItem.resourceId"
                "resource_type" : "$.detail.configurationItem.resourceType"
              InputTemplate: | 
                "On <configurationItemCaptureTime> AWS Config service recorded a creation of a new <resource_type> with Id <resource_ID> in the account <awsAccountId> region <awsRegion>. For more details open the AWS Config console at https://console.aws.amazon.com/config/home?region=<awsRegion>#/timeline/<resource_type>/<resource_ID>/configuration            Please verify if this is a valid creation."


